const QUESTION = {
    FETCH: 'QUESTION_FETCH',
    FETCH_ERROR: 'QUESTION_FETCH_ERROR',
    FETCH_SUCCESS: 'QUESTION_FETCH_SUCCESS',
    SUBMIT_SUCCESS: 'QUESTION_SUBMIT_SUCCESS'
}

export {QUESTION};